---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-main
  namespace: network
spec:
  serviceAccountName: nginx-sa
  interval: 30m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: ingress-nginx
      version: 4.12.3
      sourceRef:
        kind: HelmRepository
        name: nginx
      interval: 30m
  valuesFrom:
    - kind: ConfigMap
      name: nginx-values
      valuesKey: values.yaml