apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-main
  namespace: network
spec:
  serviceAccountName: nginx-sa
  interval: 30m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: ingress-nginx
      version: '4.12.3'
      sourceRef:
        kind: HelmRepository
        name: nginx
        namespace: flux-system
      interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controller:
      serviceAccount:
        create: false
        name: nginx-sa
      ingressClassResource:
        name: nginx-main
      ingressClass: nginx-main
      service:
        type: LoadBalancer
