apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-operator
  namespace: database
spec:
  values:
    # Cluster-specific config dla svm-k8s-lab
    monitoring:
      podMonitorEnabled: true

    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 1Gi
