apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-operator
  namespace: database
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudnative-pg
      version: '0.x'
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
    cleanupOnFail: true
  values:
    # Domyślne wartości dla CNPG operator
    config:
      data:
        INHERITED_ANNOTATIONS: ".*"
        INHERITED_LABELS: ".*"

    monitoring:
      podMonitorEnabled: false

    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
