apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: monitoring
spec:
  values:
    # Cluster-specific config dla svm-k8s-lab
    controller:
      type: deployment  # Zamiast daemonset dla lab
      replicas: 1

    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 1Gi
